AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dialer Cloud Formation Template with nested stacks

Resources:

  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/template.yaml

      
  Lambda:
    Type: AWS::Serverless::Application
    DependsOn: Cognito
    Properties:
      Location: lambdas/template.yaml
      Parameters: 
          UserPoolID: !GetAtt Cognito.Outputs.UserPoolId
          ClientID: !GetAtt Cognito.Outputs.ClientId

  
  Api:
    Type: AWS::Serverless::Application
    DependsOn: Lambda
    Properties:
      Location: api/template.yaml
      Parameters: 
          CognitoSignUpFunctionUri: !GetAtt Lambda.Outputs.CognitoSignUpFunctionUri
          CognitoSignUpFunctionArn: !GetAtt Lambda.Outputs.CognitoSignUpFunctionArn
          UserPoolARN: !GetAtt Cognito.Outputs.UserPoolArn